version: '3.9'
services:
  osint:
    container_name: osint
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./config/gh:/root/.config/gh
      - .:/app
    env_file:
      - osing.env
